class PropConstants:

    ROTATION_ENABLE_DEFAULT = True
    PRE_ROTATION_DISABLE_DEFAULT = False

    ROTATION_STEP_MIN = 1
    ROTATION_STEP_MAX = 180
    ROTATION_STEP_DEFAULT = 90

    PIXEL_MARGIN_MIN = 1
    PIXEL_MARGIN_MAX = 100
    PIXEL_MARGIN_DEFAULT = 5

    PIXEL_PADDING_MIN = 0
    PIXEL_PADDING_MAX = 100
    PIXEL_PADDING_DEFAULT = 0

    EXTRA_PIXEL_MARGIN_TO_OTHERS_MIN = 0
    EXTRA_PIXEL_MARGIN_TO_OTHERS_MAX = 100
    EXTRA_PIXEL_MARGIN_TO_OTHERS_DEFAULT = 0

    PIXEL_MARGIN_TEX_SIZE_MIN = 16
    PIXEL_MARGIN_TEX_SIZE_MAX = 16384	
    PIXEL_MARGIN_TEX_SIZE_DEFAULT = 1024

    TILES_IN_ROW_DEFAULT = 10
    TILE_COUNT_PER_GROUP_DEFAULT = 1
    LAST_GROUP_COMPLEMENTARY_DEFAULT = False
    GROUP_COMPACTNESS_DEFAULT = 0.0
    